"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
// Next.jsのヘッドコンポーネントをインポート
import Head from "next/head";
import Link from "next/link";
import { useSelectedLayoutSegment } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  auth,
  children,
}: Readonly<{
  auth: React.ReactNode;
  children: React.ReactNode;
}>) {
  const loginSegments = useSelectedLayoutSegment("auth");
  return (
    <html lang="ja">
      <body>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <nav>
          <Link href="/login">Open modal</Link>
        </nav>
        <div>{auth}</div>
        <div>{children}</div>
      </body>
    </html>
  );
}
